my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: [UYWNUZJ.INVISO_PARTNER] # Snowflake <account_name>
      user: [frederik.sorensen@devoteam.com] # Snowflake username
      role: [IDP_FREDERIKSORENSEN] # Snowflake user role

      # SSO config
      authenticator: externalbrowser

      database: [IDP] # Snowflake database name
      warehouse: [IDP_WH] # Snowflake warehouse name
      schema: [dbt schema]
      threads: [between 1 and 8]
      client_session_keep_alive: False
      query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false
  